import type { Metadata } from "next";
import '@/app/ui/global.css';

import {shareTechMono} from '@/app/ui/fonts';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang={"fr"}>
        <body className={`${shareTechMono.className} antialiased`}>
            {children}
        </body>
    </html>
  );
}
